### ISSUE TITLE
Add business logic for address annotation

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/nlp-sandbox-physical-address-annotator-example#5]
- Find addresses in clinical notes
- Set the PhysicalAddressAnnotation.type with values from this [enum](https://github.com/Sage-Bionetworks/nlp-sandbox-schemas/blob/develop/openapi/commons/components/schemas/PhysicalAddressAnnotation.yaml)

Use the implementation of the person name annotator as the reference:
https://github.com/Sage-Bionetworks/nlp-sandbox-person-name-annotator-example/blob/develop/server/openapi_server/controllers/person_name_controller.py

**Comment by gkowalski** [comment]
As we discussed I will complete 2 of the types of PhysicalAddressAnnotation as an example.

**Comment by tschaffter** [comment]
Thanks @gkowalski
